In [1]:
import polars as pl

# Create a data frame to test with
data = pl.DataFrame({"celsius": [10,20,30,40], "weather": ['sun', 'sun', 'rain', 'rain']})
data

shape: (4, 2)
┌─────────┬─────────┐
│ celsius ┆ weather │
│ ---     ┆ ---     │
│ i64     ┆ str     │
╞═════════╪═════════╡
│ 10      ┆ sun     │
│ 20      ┆ sun     │
│ 30      ┆ rain    │
│ 40      ┆ rain    │
└─────────┴─────────┘

In [6]:
# Use native expressions API to perform an operation on the entire celsius column
data = data.with_columns(((pl.col('celsius') * 9 / 5) + 32).alias('fahrenheit'))

data

shape: (4, 3)
┌─────────┬─────────┬────────────┐
│ celsius ┆ weather ┆ fahrenheit │
│ ---     ┆ ---     ┆ ---        │
│ i64     ┆ str     ┆ f64        │
╞═════════╪═════════╪════════════╡
│ 10      ┆ sun     ┆ 50.0       │
│ 20      ┆ sun     ┆ 68.0       │
│ 30      ┆ rain    ┆ 86.0       │
│ 40      ┆ rain    ┆ 104.0      │
└─────────┴─────────┴────────────┘

In [11]:
# Even complicated functions that operate on a row can be done calculated using
# the native expressions API:

# Example function:
def should_go_to_beach(row):
  # We will only go to the beach if it's sunny and warm
  if row['weather'] == 'sun' and row['celsius'] >= 20:
    return True
  else:
    return False

# Native expressions api:
data = data.with_columns(
    ((pl.col('weather') == 'sun' ) & (pl.col('celsius') >= 20)).alias('beach_trip')
)
data

shape: (4, 4)
┌─────────┬─────────┬────────────┬────────────┐
│ celsius ┆ weather ┆ fahrenheit ┆ beach_trip │
│ ---     ┆ ---     ┆ ---        ┆ ---        │
│ i64     ┆ str     ┆ f64        ┆ bool       │
╞═════════╪═════════╪════════════╪════════════╡
│ 10      ┆ sun     ┆ 50.0       ┆ false      │
│ 20      ┆ sun     ┆ 68.0       ┆ true       │
│ 30      ┆ rain    ┆ 86.0       ┆ false      │
│ 40      ┆ rain    ┆ 104.0      ┆ false      │
└─────────┴─────────┴────────────┴────────────┘