In [11]:
import polars as pl

# Create a data frame to test with
data = pl.DataFrame({"celsius": [10,20,30,40], "weather": ['sun', 'sun', 'rain', 'rain']})
data

shape: (4, 2)
┌─────────┬─────────┐
│ celsius ┆ weather │
│ ---     ┆ ---     │
│ i64     ┆ str     │
╞═════════╪═════════╡
│ 10      ┆ sun     │
│ 20      ┆ sun     │
│ 30      ┆ rain    │
│ 40      ┆ rain    │
└─────────┴─────────┘

In [12]:
# Define a function that takes one column and returns the conversion
def convert_to_f(col):
  return (col * 9/5) + 32

# Apply the function to each element in the celsius column
data = data.with_columns(convert_to_f(pl.col('celsius')).alias('fahrenheit'))
data

shape: (4, 3)
┌─────────┬─────────┬────────────┐
│ celsius ┆ weather ┆ fahrenheit │
│ ---     ┆ ---     ┆ ---        │
│ i64     ┆ str     ┆ f64        │
╞═════════╪═════════╪════════════╡
│ 10      ┆ sun     ┆ 50.0       │
│ 20      ┆ sun     ┆ 68.0       │
│ 30      ┆ rain    ┆ 86.0       │
│ 40      ┆ rain    ┆ 104.0      │
└─────────┴─────────┴────────────┘

In [13]:
# Do this with native expressions instead.
#
# There is no real advantage to using one way over the other
data = data.with_columns(((pl.col('celsius') * 9 / 5) + 32).alias('fahrenheit'))
data

shape: (4, 3)
┌─────────┬─────────┬────────────┐
│ celsius ┆ weather ┆ fahrenheit │
│ ---     ┆ ---     ┆ ---        │
│ i64     ┆ str     ┆ f64        │
╞═════════╪═════════╪════════════╡
│ 10      ┆ sun     ┆ 50.0       │
│ 20      ┆ sun     ┆ 68.0       │
│ 30      ┆ rain    ┆ 86.0       │
│ 40      ┆ rain    ┆ 104.0      │
└─────────┴─────────┴────────────┘

In [14]:
# Define a function that expects a row of data and calculates a result based on
# different columns in that row:
def should_go_to_beach(weather, celsius):
  # We will only go to the beach if it's sunny and warm
  return (weather == 'sun') & (celsius >= 20)

# Here we apply the function to the entire DataFrame rather than a single
# column
data = data.with_columns(should_go_to_beach(pl.col('weather'), pl.col('celsius')).alias('beach_trip'))
data

shape: (4, 4)
┌─────────┬─────────┬────────────┬────────────┐
│ celsius ┆ weather ┆ fahrenheit ┆ beach_trip │
│ ---     ┆ ---     ┆ ---        ┆ ---        │
│ i64     ┆ str     ┆ f64        ┆ bool       │
╞═════════╪═════════╪════════════╪════════════╡
│ 10      ┆ sun     ┆ 50.0       ┆ false      │
│ 20      ┆ sun     ┆ 68.0       ┆ true       │
│ 30      ┆ rain    ┆ 86.0       ┆ false      │
│ 40      ┆ rain    ┆ 104.0      ┆ false      │
└─────────┴─────────┴────────────┴────────────┘

In [15]:
# And an inline version:
data = data.with_columns(((pl.col('weather') == 'sun') & (pl.col('celsius') >= 20)).alias('beach_trip'))
data

shape: (4, 4)
┌─────────┬─────────┬────────────┬────────────┐
│ celsius ┆ weather ┆ fahrenheit ┆ beach_trip │
│ ---     ┆ ---     ┆ ---        ┆ ---        │
│ i64     ┆ str     ┆ f64        ┆ bool       │
╞═════════╪═════════╪════════════╪════════════╡
│ 10      ┆ sun     ┆ 50.0       ┆ false      │
│ 20      ┆ sun     ┆ 68.0       ┆ true       │
│ 30      ┆ rain    ┆ 86.0       ┆ false      │
│ 40      ┆ rain    ┆ 104.0      ┆ false      │
└─────────┴─────────┴────────────┴────────────┘